name: Upload to NEAR AI Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check version update
        run: |
          # Get version from current metadata.json
          CURRENT_VERSION=$(jq -r .version ./agent/metadata.json)

          # Get version from previous commit
          git checkout HEAD^
          PREVIOUS_VERSION=$(jq -r .version ./agent/metadata.json)
          git checkout -

          if [ "$CURRENT_VERSION" == "$PREVIOUS_VERSION" ]; then
            echo "::error::Version in metadata.json must be updated before pushing to main branch. Current version: $CURRENT_VERSION"
            exit 1
          else
            echo "Version updated from $PREVIOUS_VERSION to $CURRENT_VERSION"
          fi

  upload:
    # Only run upload job on push to main, not on PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: check_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install NEAR AI CLI
        run: pip install nearai

      - name: Login to NEAR AI
        run: |
          nearai login --accountId ${{ secrets.NEAR_ACCOUNT_ID }} --privateKey ${{ secrets.NEAR_PRIVATE_KEY }}

      - name: Upload to Registry
        run: |
          nearai registry upload ./agent
