name: Upload to NEAR AI Registry

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install NEAR AI CLI
        run: pip install nearai

      - name: Login to NEAR AI
        run: |
          nearai login --accountId ${{ secrets.NEAR_ACCOUNT_ID }} --privateKey ${{ secrets.NEAR_PRIVATE_KEY }}

      - name: Upload to Registry
        run: |
          # Assuming your agent/item is in the root directory
          nearai registry upload .
